/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 models/lily_flower.gltf --transform
Files: models/lily_flower.gltf [410.78KB] > lily_flower-transformed.glb [23.9KB] (94%)
*/
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Cube_2: THREE.Mesh;
    mesh_1: THREE.InstancedMesh;
    mesh_2: THREE.InstancedMesh;
    mesh_3: THREE.InstancedMesh;
  };
  materials: {};
};

type Props = JSX.IntrinsicElements["group"] & {
  customMaterial?: THREE.Material;
};

export function LilyFlower({ customMaterial, ...rest }: Props) {
  const { nodes, materials } = useGLTF(
    "/models/lily_flower-transformed.glb",
  ) as GLTFResult;

  return (
    <group {...rest} dispose={null}>
      <mesh
        geometry={nodes.Cube_2.geometry}
        material={nodes.Cube_2.material}
        position={[-2.459, 2.215, 1.645]}
        rotation={[-Math.PI, Math.PI / 3, -2.644]}
        scale={0.01}
      />
      <instancedMesh
        args={[nodes.mesh_1.geometry, nodes.mesh_1.material, 7]}
        instanceMatrix={nodes.mesh_1.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.mesh_2.geometry, nodes.mesh_2.material, 7]}
        instanceMatrix={nodes.mesh_2.instanceMatrix}
      />
      <instancedMesh
        args={[nodes.mesh_3.geometry, nodes.mesh_3.material, 7]}
        instanceMatrix={nodes.mesh_3.instanceMatrix}
      />
    </group>
  );
}

useGLTF.preload("/models/lily_flower-transformed.glb");
